### ISSUE TITLE
wont work unless you have SDL2 installed :)

### ISSUE THREAD

**Issue by r-lyeh** [fungos/ass#1]
because of...
https://github.com/fungos/ass/blob/e9d925db0ba2aee909bba2eb72e30ab56c74410e/ass.h#L5

also, many embedded files assume that some backends are present, like openal:

https://github.com/fungos/ass/blob/master/ass.cpp#L1462

these cases would behave better embraced with #if WITH_xxx  / #endif directives imho.

**Comment by fungos** [comment]
Thanks. I had forced the backends by platform before to be easier to use (to me), but best to let it off and people will see the SoLoud error message asking for a backend.

This and some other issues are fixed, it should be a little better now.
